/*
 * File: app/store/LocalStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

<<<<<<< HEAD
Ext.define('LocalBuzzMerchantDemo.store.LocalStore', {
	extend: 'Ext.data.Store',

	requires: [
		'LocalBuzzMerchantDemo.model.Deal'
	],

	config: {
		model: 'LocalBuzzMerchantDemo.model.Deal',
		storeId: 'LocalStore'
	}
=======
Ext.define('Contact.store.LocalStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Contact.model.Deal'
    ],

    config: {
        model: 'Contact.model.Deal',
        storeId: 'LocalStore'
    }
>>>>>>> 9aa003d17072fb2b35719aa33fba9abae5e66c2b
});