/*
 * File: app/store/MyDealsStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

<<<<<<< HEAD
Ext.define('LocalBuzzMerchantDemo.store.MyDealsStore', {
	extend: 'Ext.data.Store',

	requires: [
		'LocalBuzzMerchantDemo.model.Deal',
		'Ext.data.proxy.JsonP',
		'Ext.data.reader.Json',
		'Ext.data.writer.Json'
	],

	config: {
		autoLoad: true,
		model: 'LocalBuzzMerchantDemo.model.Deal',
		storeId: 'MyDealsStore',
		proxy: {
			type: 'jsonp',
			timeout: 300000,
			url: 'http://services.appsonmobile.com/demoDeals',
			reader: {
				type: 'json'
			},
			writer: {
				type: 'json',
				encode: true
			}
		},
		listeners: [
			{
				fn: 'onJsonstoreAddrecords',
				event: 'addrecords'
			},
			{
				fn: 'onJsonstoreRemoverecords',
				event: 'removerecords'
			}
		]
	},

	onJsonstoreAddrecords: function(store, records, eOpts) {

	},

	onJsonstoreRemoverecords: function(store, records, indices, eOpts) {
		store.load();

	}

=======
Ext.define('Contact.store.MyDealsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Contact.model.Deal',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        autoLoad: true,
        model: 'Contact.model.Deal',
        storeId: 'MyDealsStore',
        proxy: {
            type: 'jsonp',
            extraParams: '{customerId}',
            url: 'http://awseb-e-t-awsebloa-6jvxjux3fp3k-1527799463.us-west-2.elb.amazonaws.com/deals',
            reader: {
                type: 'json'
            }
        }
    }
>>>>>>> 9aa003d17072fb2b35719aa33fba9abae5e66c2b
});