/*
 * File: app/view/ChangeContactPicForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LocalBuzzMerchantDemo.view.ChangeContactPicForm', {
	extend: 'Ext.form.Panel',
	alias: 'widget.ChangeContactPicForm',

	requires: [
		'Ext.field.File',
		'Ext.Button',
		'Ext.field.Text'
	],

	config: {
		centered: true,
		height: '40%',
		id: 'ChangeContactPicForm',
		itemId: 'ChangeContactPicForm',
		style: 'background;#fff;border:3px groove #1985d0',
		styleHtmlContent: true,
		width: '80%',
		hideOnMaskTap: true,
		modal: true,
		scrollable: false,
		layout: {
			type: 'vbox',
			align: 'stretchmax',
			pack: 'end'
		},
		items: [
			{
				xtype: 'filefield',
				cls: 'customfield1',
				itemId: 'myfilefield1',
				margin: '5 5 5 5',
				styleHtmlContent: true,
				width: 214,
				clearIcon: false,
				label: '',
				labelWrap: true,
				name: 'fileUpload',
				accept: 'image',
				capture: 'camera'
			},
			{
				xtype: 'button',
				handler: function(button, e) {
					var form = this.up('ChangeContactPicForm');




					var record = form.getRecord();
					var customerId= form.getRecord().get('customerId');


					var store = Ext.getStore('MyJsonPStore');
					var file= form.getAt(0).getValue();

					if(file){

						form.submit({

							url: 'http://services.appsonmobile.com/demoStores/' + customerId ,
							xhr2:true,
							cache: false,
							waitMsg : 'Please Wait...',
							success: function(form,action){

								//var view = Ext.Viewport.getActiveItem();

								/*record.setDirty();

								record.beginEdit(true,record.getChanges());

								form.updateRecord(record);

								record.endEdit(true,record.getChanges());


								record.commit();*/

								store.sync();
								store.load();


								Ext.Msg.alert('Record updated', "Please login again to see the changes",null,null);

								Ext.Viewport.getComponent('formpanel').setRecord(record);
								form.destroy();

								//view.setRecord(record);





							},
							failure: function(form,action) {

								store.load();
								Ext.Msg.alert('Oops.....!Something went wrong','Please check your internet connection or try again later',null,null);



								form.destroy();

							},


						});
					}
					else {

						Ext.Msg.alert('Error!','No image to upload ',null,null);

					}




				},
				bottom: 30,
				centered: false,
				cls: 'button',
				height: '23%',
				left: '25%',
				margin: '',
				style: 'font-size:5vw!important',
				styleHtmlContent: true,
				ui: 'action',
				width: 128,
				iconAlign: 'center',
				text: 'Submit'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'customerId'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'businessName'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'category'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'phoneNumber'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'address'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'emailAddress'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'loginEmail'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'zipcode'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'state'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'city'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'pictureURL'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'website'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'websiteDisplayName'
			}
		],
		listeners: [
			{
				fn: 'onChangeContactPicFormHiddenChange',
				event: 'hiddenchange'
			}
		]
	},

	onChangeContactPicFormHiddenChange: function(component, value, oldValue, eOpts) {


		if(component.isHidden()===true && oldValue!==null){

			component.destroy();
		}

	}

});