/*
 * File: app/view/CreateNewBuzzOption.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LocalBuzzMerchantDemo.view.CreateNewBuzzOption', {
	extend: 'Ext.Panel',
	alias: 'widget.CreateNewBuzzOption',

	requires: [
		'Ext.Button'
	],

	config: {
		id: 'CreateNewBuzzOption',
		itemId: 'CreateNewBuzzOption',
		items: [
			{
				xtype: 'button',
				handler: function(button, e) {
					var storeUserDetails = Ext.getStore('UserDetails');
					storeUserDetails.load();
					var customerId;
					var businessName;
					var DealPictureURL ;
					var city;
					var state;



					Ext.Viewport.getActiveItem().destroy();
					var view = Ext.Viewport.add({xtype: 'CreateNewBuzzWithImage'});
					storeUserDetails.each(function(record){
						//console.log('StoreUserDetails : ' +record.get('customerId'));
						customerId = record.get('customerId');
						businessName = record.get('businessName');
						DealPictureURL = record.get('DealPictureURL');
						city= record.get('city');
						state= record.get('state');

						view.setRecord(record);
					});

					Ext.Viewport.setActiveItem(view);

				},
				height: '9vh',
				left: '20%',
				styleHtmlContent: true,
				top: '30%',
				ui: 'action',
				width: '65%',
				text: 'Create Buzz With Image'
			},
			{
				xtype: 'button',
				handler: function(button, e) {
					var storeUserDetails = Ext.getStore('UserDetails');
					storeUserDetails.load();
					var customerId;
					var businessName;
					var DealPictureURL ;
					var city;
					var state;


					Ext.Viewport.getActiveItem().destroy();
					var view = Ext.Viewport.add({xtype: 'CreateNewBuzzNoImage'});
					storeUserDetails.each(function(record){
						//console.log('StoreUserDetails : ' +record.get('customerId'));
						customerId = record.get('customerId');
						businessName = record.get('businessName');
						DealPictureURL = record.get('DealPictureURL');
						city= record.get('city');
						state= record.get('state');
						view.setRecord(record);
					});

					Ext.Viewport.setActiveItem(view);

				},
				height: '9vh',
				left: '20%',
				styleHtmlContent: true,
				top: '50%',
				ui: 'action',
				width: '65%',
				text: 'Create Buzz No Image'
			}
		]
	}

});