/*
 * File: app/view/DealPicture.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.DealPicture', {
    extend: 'Ext.Container',
    alias: 'widget.dealpicture',

    alternateClassName: [
        'dealPicture'
    ],
    requires: [
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        fullscreen: true,
        id: 'dealPicture',
        itemId: 'dealPicture',
        style: 'background:#fff',
        layout: 'fit',
        scrollable: true,
        tpl: [
            '<img src="{dealPictureURL}" />'
        ],
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.getStore('LocalStore').removeAt(0);
                            Ext.Viewport.getActiveItem().destroy();
                            var view = Ext.Viewport.add({xtype:'DealsPanel'});
                            Ext.Viewport.setActiveItem(view);

                        },
                        style: 'border:none;font-size:8vw',
                        ui: 'plain',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        itemId: 'share',
                        style: 'border:none;font-size:7vw',
                        ui: 'plain',
                        iconCls: 'action'
                    }
                ]
            }
        ]
    }

});