/*
 * File: app/view/DealsPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.DealsPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.DealsPanel',

    requires: [
        'Contact.view.ListOfDeals',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List'
    ],

    config: {
        height: '100%',
        padding: '5 5 5 5',
        style: 'background:#fff',
        scrollable: false,
        layout: {
            type: 'vbox',
            align: 'stretchmax',
            pack: 'center'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'dealBackBtn',
                        style: 'border:none;font-size:8vw',
                        ui: 'plain',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'listofdeals',
                height: '90%',
                minHeight: '90%',
                flex: 1
            }
        ]
    }

});