/*
 * File: app/view/DealImage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LocalBuzzMerchantDemo.view.DealImage', {
	extend: 'Ext.Panel',
	alias: 'widget.DealImage',

	requires: [
		'Ext.XTemplate',
		'Ext.Toolbar',
		'Ext.Button'
	],

	config: {
		height: '80%',
		id: 'DealImage',
		itemId: 'DealImage',
		style: 'background:#FFF;border:1px solid #00529D',
		width: '95%',
		scrollable: true,
		tpl: [
			'<div id="wrapper" style="margin:0px 0px 0px 0px;height:100%;width:100%">',
			'	',
			'	<tpl if="dealImageURL">',
			'	<div id="scroller"><img src="{dealImageURL}" style="margin:0px 0px 0px 0px;height:100%;width:100%"/></div>',
			'                            ',
			'		</tpl>',
			'		',
			'	</div>'
		],
		layout: {
			type: 'vbox',
			align: 'stretchmax'
		},
		items: [
			{
				xtype: 'toolbar',
				cls: 'toolbarCls',
				docked: 'top',
				height: '8vh',
				items: [
					{
						xtype: 'button',
						handler: function(button, e) {
							Ext.Viewport.getComponent('DealImage').destroy();

						},
						cls: 'icon-close',
						docked: 'right',
						id: 'close',
						itemId: 'close',
						padding: '10 10 10 10',
						style: 'color:#00529D;font-size:5vw',
						ui: 'plain'
					}
				]
			}
		],
		listeners: [
			{
				fn: 'onDealImageShow',
				event: 'show'
			}
		]
	},

	onDealImageShow: function(component, eOpts) {
		var myScroll = new IScroll('#wrapper', {
				zoom: true,
				scrollX: true,
				scrollY: true,
				mouseWheel: true,
				wheelAction: 'zoom'
			});
	}

});