/*
 * File: app/view/DealsPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.DealsPanel', {
	extend: 'Ext.form.Panel',
	alias: 'widget.DealsPanel',

	requires: [
		'Contact.view.ListOfDeals',
		'Ext.dataview.List',
		'Ext.Button'
	],

	config: {
		baseCls: 'x-list',
		id: 'dealsPanel',
		itemId: 'dealsPanel',
		minHeight: '80%',
		padding: '5 5 5 5',
		style: 'border:1px inset;',
		styleHtmlContent: true,
		url: '',
		items: [
			{
				xtype: 'listofdeals',
				docked: 'top',
				height: '90%',
				itemId: 'listofdeals',
				width: '100%'
			},
			{
				xtype: 'button',
				docked: 'bottom',
				height: '7%',
				id: 'UploadDeal',
				itemId: 'UploadDeal',
				margin: '5 5 5 5',
				style: 'font-size:5vw',
				ui: 'confirm',
				width: '',
				text: 'Create Buzz'
			}
		],
		listeners: [
			{
				fn: 'onDealsPanelActivate',
				event: 'activate'
			}
		]
	},

	onDealsPanelActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
		console.log('Deals Panel Activated');
		var storeUserDetails = Ext.getStore('UserDetails');
		storeUserDetails.load();
		var customerId;
		var businessName;
		var date = new Date();

		var today = Ext.Date.format(date, 'n/j/Y');

		storeUserDetails.each(function(record){
			//console.log('StoreUserDetails : ' +record.get('customerId'));
			customerId = record.get('customerId');
			businessName = record.get('businessName');

		});

		console.log(customerId);
		var store = Ext.getStore('MyDealsStore');
		store.clearFilter();
		store.filter('customerId',customerId);

		 var records= [];


		        store.each(function(rec)
		                   {


							   //console.log('Deal End Date: ' + rec.get('dealEndDate'));
							   //console.log('Tdays date is : ' + today);
		                       /*if(rec.get('dealEndDate') >= today) {

		                           records.push(rec.get('itemName'));
								   //console.log('Active deal ' + rec.get('dealName'));


		                       }
		                       else {
		                           Ext.Array.remove(records,rec.get('itemName'));
								   //console.log('Expired deal ' + rec.get('dealName'));
								   var req = Ext.Ajax.request({

						method:'POST',


						url  : 'http://services.appsonmobile.com/deals/'+ rec.get('itemName')

			});


		                       }*/

							   if(rec.get('dealEndDate') < today) {

								   Ext.Ajax.request({

						method:'POST',


						url  : 'http://services.appsonmobile.com/deals/'+ rec.get('itemName')



							   });





							   }});
		store.load();
		    /* store.clearFilter();

		      console.log(records.length);

		        store.filterBy(function(record){
		            return Ext.Array.indexOf(records, record.get('itemName')) !== -1;

		        }, this);*/




	}

});