/*
 * File: app/view/Info.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Info', {
    extend: 'Ext.form.Panel',
    alias: 'widget.contactinfo',

    requires: [
        'Contact.view.Picture',
        'Contact.view.ListOfDeals',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Panel',
        'Ext.field.TextArea',
        'Ext.dataview.List'
    ],

    config: {
        border: 5,
        enableSubmissionForm: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                style: 'font-size:6vw',
                ui: 'light',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'infoBackBtn',
                        style: '',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer',
                        height: 11,
                        width: 18
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: 'contact-name',
                        disabled: true,
                        html: '<b>First Name</b>',
                        itemId: 'nameTxt',
                        style: ''
                    }
                ]
            },
            {
                xtype: 'panel',
                border: '',
                height: '',
                maxHeight: '100%',
                minHeight: '100%',
                minWidth: '',
                padding: '5 5 5 5',
                style: 'border:1px inset',
                layout: {
                    type: 'vbox',
                    align: 'end'
                },
                items: [
                    {
                        xtype: 'contactpic',
                        border: '',
                        docked: 'left',
                        height: 137,
                        maxHeight: '100%',
                        minHeight: '50%',
                        minWidth: '30%',
                        style: '',
                        ui: 'light',
                        width: 97,
                        scrollable: false,
                        flex: 0.5,
                        layout: {
                            type: 'hbox',
                            align: 'start',
                            pack: 'center'
                        }
                    },
                    {
                        xtype: 'panel',
                        height: '',
                        maxHeight: '100%',
                        minHeight: '100%',
                        width: '100%',
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'icon-phone',
                                    'customfield'
                                ],
                                height: '',
                                itemId: 'phoneNumber',
                                maxHeight: '30%',
                                maxWidth: '100%',
                                minHeight: '',
                                minWidth: '100%',
                                width: '100%',
                                clearIcon: false,
                                inputCls: 'customfield',
                                name: 'phoneNumber',
                                readOnly: true
                            },
                            {
                                xtype: 'spacer',
                                height: '10px'
                            },
                            {
                                xtype: 'textareafield',
                                cls: [
                                    'icon-location',
                                    'customfield'
                                ],
                                height: '100%',
                                itemId: 'address',
                                maxHeight: '100%',
                                maxWidth: '100%',
                                minHeight: '100%',
                                minWidth: '100%',
                                style: 'border:1 px inset',
                                width: '100%',
                                clearIcon: false,
                                inputCls: 'customfield',
                                name: 'address',
                                readOnly: true,
                                maxRows: 3
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                padding: '5 5 5 5',
                style: 'border:1px inset',
                items: [
                    {
                        xtype: 'listofdeals',
                        border: '',
                        cls: 'list-item',
                        style: '',
                        itemCls: 'list-item'
                    }
                ]
            }
        ]
    },

    setRecord: function(record) {
        this.callParent(arguments);
        if (record) {
            var name = record.get('businessName');
           var isFavorite = record.get('isFavorite');

            this.down('#nameTxt').setHtml(name);
            //this.down('#favlist')[isFavorite ? 'addCls' : 'removeCls']('empty-star');
           // this.down('#favoriteBtn')[isFavorite ? 'addCls' : 'removeCls']('x-button-pressed');
            this.down('contactpic').setData(record.data);

            var customerId = record.get('customerId');
            var ds = Ext.StoreManager.lookup('MyDealsStore');
            ds.clearFilter() ;
            ds.filter('customerId', customerId);
            /*dealsData  = ds.getData().getAt(0);
            var dealName = 'No Deals';
            if(dealsData) {
                 dealName = dealsData.get('dealName');
            }*/
           this.down('listofdeals').setData(ds.getData()) ;



        }


    }

});