/*
 * File: app/view/Info.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Info', {
    extend: 'Ext.form.Panel',
    alias: 'widget.contactinfo',

    requires: [
        'Contact.view.Picture',
        'Contact.view.ListOfDeals',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.field.Text',
        'Ext.dataview.List'
    ],

    config: {
        border: 5,
        enableSubmissionForm: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'infoBackBtn',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: 'contact-name',
                        disabled: true,
                        html: 'First Name Last Name',
                        itemId: 'nameTxt'
                    }
                ]
            },
            {
                xtype: 'panel',
                border: '',
                docked: 'top',
                height: 162,
                scrollable: false,
                layout: {
                    type: 'hbox',
                    align: 'start'
                },
                items: [
                    {
                        xtype: 'contactpic',
                        docked: 'left',
                        height: 146,
                        ui: 'light',
                        width: 127,
                        scrollable: false,
                        flex: 0.5,
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        }
                    },
                    {
                        xtype: 'formpanel',
                        flex: 3,
                        docked: 'right',
                        height: 144,
                        itemId: 'myformpanel',
                        style: 'background: transparent',
                        width: '50%',
                        scrollable: false,
                        enableSubmissionForm: false,
                        layout: {
                            type: 'vbox',
                            align: 'start',
                            pack: 'end'
                        },
                        items: [
                            {
                                xtype: 'textfield',
                                flex: 2,
                                cls: 'icon-phone',
                                itemId: 'phoneNumber',
                                style: 'opacity : 0.5;',
                                inputCls: '',
                                label: '',
                                name: 'phoneNumber',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                flex: 2,
                                cls: 'icon-info',
                                itemId: 'emailAddress',
                                style: 'opacity :0.5;',
                                label: '',
                                name: 'emailAddress',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                flex: 4,
                                cls: 'icon-location',
                                itemId: 'address',
                                style: 'opacity:0.5',
                                label: '',
                                name: 'address',
                                readOnly: true
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'listofdeals'
            }
        ],
        listeners: [
            {
                fn: 'onPhoneNumberFocus',
                event: 'focus',
                delegate: '#phoneNumber'
            },
            {
                fn: 'onAddressFocus',
                event: 'focus',
                delegate: '#address'
            }
        ]
    },

    onPhoneNumberFocus: function(textfield, e, eOpts) {
        console.log(textfield.getValue());
        numberToDial = textfield.getValue();
        window.location = 'tel:numberToDial' ;
    },

    onAddressFocus: function(textfield, e, eOpts) {
        console.log("Text Field value is:" + textfield) ;
        Ext.view
    },

    setRecord: function(record) {
        this.callParent(arguments);
        if (record) {
            var name = record.get('businessName') + ' ' + (record.get('category') || '');
           var isFavorite = record.get('isFavorite');

            this.down('#nameTxt').setHtml(name);
            //this.down('#favlist')[isFavorite ? 'addCls' : 'removeCls']('empty-star');
           // this.down('#favoriteBtn')[isFavorite ? 'addCls' : 'removeCls']('x-button-pressed');
            this.down('contactpic').setData(record.data);

            var customerId = record.get('customerId');
            var ds = Ext.StoreManager.lookup('MyDealsStore');
            ds.clearFilter() ;
            ds.filter('customerId', customerId);
            /*dealsData  = ds.getData().getAt(0);
            var dealName = 'No Deals';
            if(dealsData) {
                 dealName = dealsData.get('dealName');
            }*/
           this.down('listofdeals').setData(ds.getData()) ;



        }


    }

});