/*
 * File: app/view/ListOfDeals.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LocalBuzzMerchantDemo.view.ListOfDeals', {
	extend: 'Ext.dataview.List',
	alias: 'widget.listofdeals',

	requires: [
		'Ext.XTemplate'
	],

	config: {
		cls: 'customlist',
		height: '100%',
		id: 'ListOfDeals',
		itemId: 'ListOfDeals',
		autoDestroy: false,
		allowDeselect: true,
		deselectOnContainerClick: false,
		mode: 'MULTI',
		deferEmptyText: false,
		emptyText: 'Create a Buzz!',
		itemCls: 'list-item',
		store: 'MyDealsStore',
		pinHeaders: false,
		preventSelectionOnDisclose: false,
		refreshHeightOnUpdate: false,
		useSimpleItems: false,
		itemTpl: [
			'',
			'',
			'<div style="font-size:5vw;color:black;font-weight:normal;font-family:Arial">{dealName}<button type="button" id="delete" class="delete_button" style="float:right;padding:0px 15px 0px 15px;">#<button type="button" id="edit" class="delete_button" style="float:right">p</div>',
			'<tpl if="dealEndDate &lt; todayplusthreedays ">',
			'<div class= expiringDate >Valid {dealStartDate} to {dealEndDate}</div>',
			'<tpl else>	',
			'<div class= dateValidity >Valid {dealStartDate} to {dealEndDate}</div></tpl>',
			''
		]
	}

});