/*
 * File: app/view/ListOfDeals.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.ListOfDeals', {
    extend: 'Ext.dataview.List',
    alias: 'widget.listofdeals',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        height: 247,
        id: 'ListOfDeals',
        store: 'MyDealsStore',
        onItemDisclosure: false,
        striped: true,
        useSimpleItems: false,
        itemTpl: [
            '<div>{dealName}</div>',
            '<div>{dealStartDate} - {dealEndDate}</div>'
        ]
    }

});