/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LocalBuzzMerchantDemo.view.Login', {
	extend: 'Ext.Container',
	alias: 'widget.Login',

	config: {
		hidden: false,
		id: 'Login',
		itemId: 'Login',
		maxHeight: '',
		style: '',
		styleHtmlContent: true,
		layout: {
			type: 'card',
			animation: 'pop'
		},
		listeners: [
			{
				fn: 'onContainerPainted',
				event: 'painted'
			}
		]
	},

	onContainerPainted: function(element, eOpts) {




		// Settings.
		FacebookInAppBrowser.settings.appId = '900651756709444';
		FacebookInAppBrowser.settings.redirectUrl = 'http://www.appsonmobile.com';
		FacebookInAppBrowser.settings.permissions = 'email';

		// Optional
		FacebookInAppBrowser.settings.timeoutDuration = 7500;



		// Login(accessToken will be stored trough localStorage in 'accessToken');
		FacebookInAppBrowser.login({
			send: function() {
				console.log('login opened');
			},
			success: function(access_token) {
				console.log('done, access token: ' + access_token);
				Ext.Viewport.getComponent('WelcomeScreen').destroy();


			},
			denied: function() {
				console.log('user denied');
			},
			timeout: function(){
				console.log('a timeout has occurred, probably a bad internet connection');
			},
			complete: function(access_token) {
				console.log('window closed');
				if(access_token) {
					console.log(access_token);
				} else {
					console.log('no access token');
				}
			},
			userInfo: function(userInfo) {

				if(userInfo) {
				var userInf = JSON.stringify(userInfo);
					console.log(userInf);

					var info = userInf.split("\",\"");

					var tmp = info[0].split("\":\"");
					var email = tmp[1];

					tmp = info[1].split("\":\"");
					var loginName = tmp[1];

					tmp = info[2].split("\":\"");
					var gender = tmp[1];

					tmp = info[3].split("\":\"");
					var userId = tmp[1];

					var record = Ext.getStore('MyJsonPStore').findRecord('loginEmail',email,0,true,false,false);

					if(!record){
						Ext.Msg.alert('Business could not be verified',"Please contact us at info@appsonmobile.com",
						function(){
							FacebookInAppBrowser.logout(function(){
								window.localStorage.setItem('facebookAccessToken',null) ;
								location.reload();
							});
						},null);

					}
					else {
						var endDate = new Date(record.get('endDate'));
						var today = new Date();
						var storeUserDetails = Ext.getStore('UserDetails');
						storeUserDetails.removeAll();
						if(record.get('signupStatus') ==="Approved") {
							if((record.get('planType')==="Free" && endDate >= today)||record.get('planType')==="Paid"){
								storeUserDetails.add({'customerId' : record.get('customerId'),
													  'email': email,
													  'businessName': record.get('businessName'),
													  'DealPictureURL': record.get('pictureURL'),
													  'city': record.get('city'),
													  'state': record.get('state')
												  });
								var view = Ext.Viewport.add({xtype:'panel'});
								Ext.Viewport.getActiveItem().destroy();
								Ext.Viewport.setActiveItem(view);

						}
						else
						{
							Ext.Msg.alert('Business could not be verified',
										  "Please contact us at info@appsonmobile.com",
										  function(){
											FacebookInAppBrowser.logout(function(){
											window.localStorage.setItem('facebookAccessToken',null) ;
											location.reload();
										});
							},null);

						}

					}
					else if(record.get('signupStatus') ==='Pending'){
						Ext.Msg.alert('Business could not be verified',
									  "Please contact us at info@appsonmobile.com",
									  function(){
									   FacebookInAppBrowser.logout(function(){
									   window.localStorage.setItem('facebookAccessToken',null) ;
									   location.reload();
										});
						},null);

					}
					else if(record.get('signupStatus') ==='Denied'){
						Ext.Msg.alert('Business could not be verified',
									   "Please contact us at info@appsonmobile.com",
									   function(){
									   FacebookInAppBrowser.logout(function(){
										 window.localStorage.setItem('facebookAccessToken',null) ;
										 location.reload();


										});
						},null);

					}
					else if(record.get('signupStatus') ==='Cancelled'){
						Ext.Msg.alert('Our records show that your account is not active',
									   "Please contact us at info@appsonmobile.com if you would like to activate your account",
									   function(){
										 FacebookInAppBrowser.logout(function(){
										 window.localStorage.setItem('facebookAccessToken',null) ;
										 location.reload();
										});
									},null);
					}
					else {
						Ext.Msg.alert('Cannot find your account',"Please contact us at info@appsonmobile.com",
									  function(){
									   FacebookInAppBrowser.logout(function(){
										window.localStorage.setItem('facebookAccessToken',null) ;
										location.reload();
										});
									},null);

					}


				}





						} else {
							console.log('no user info');
						}
					}
				});

	}

});