/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Main', {
    extend: 'Ext.tab.Panel',

    requires: [
        'Contact.view.List',
        'Contact.view.FavoriteView',
        'Ext.dataview.List',
        'Ext.tab.Bar'
    ],

    config: {
        height: '100%',
        minHeight: '',
        modal: true,
        items: [
            {
                xtype: 'container',
                title: 'Home',
                iconCls: 'home',
                ui: 'dark',
                layout: 'hbox',
                modal: true,
                items: [
                    {
                        xtype: 'contactlist',
                        modal: true,
                        flex: 1
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'My Favorites',
                iconCls: 'star',
                height: '100%',
                itemId: 'Favorites',
                modal: false,
                items: [
                    {
                        xtype: 'favoriteview',
                        height: '100%',
                        itemId: 'favoriteview1',
                        modal: false
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});