/*
 * File: app/view/Main1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Main1', {
    extend: 'Ext.Panel',

    requires: [
        'Contact.view.List',
        'Ext.Toolbar',
        'Ext.dataview.List'
    ],

    config: {
        cls: 'home',
        html: '',
        style: '',
        items: [
            {
                xtype: 'toolbar',
                cls: 'customToolbar',
                docked: 'top',
                html: '<center><img src="localbuzz.png"/></center>',
                padding: '10 0 0 0',
                style: 'font-size:5vw',
                ui: 'light'
            },
            {
                xtype: 'contactlist',
                height: 379,
                style: 'font-size:7vw',
                itemCls: 'list-items'
            }
        ]
    }

});