/*
 * File: app/view/MyPieChart.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.MyPieChart', {
	extend: 'Ext.chart.PolarChart',
	alias: 'widget.pieChart',

	requires: [
		'Ext.chart.series.Pie',
		'Ext.chart.interactions.Rotate'
	],

	config: {
		height: '100%',
		colors: [
			'#115fa6',
			'#94ae0a',
			'#a61120',
			'#ff8809',
			'#ffd13e',
			'#a61187',
			'#24ad9a',
			'#7c7474',
			'#a66111'
		],
		series: [
			{
				type: 'pie',
				labelField: 'zipcode',
				xField: 'numberOfHits',
				yField: 'zipcode'
			}
		],
		interactions: [
			{
				type: 'rotate'
			}
		]
	}

});