/*
 * File: app/view/WelcomeScreen.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LocalBuzzMerchantDemo.view.WelcomeScreen', {
	extend: 'Ext.Panel',
	alias: 'widget.WelcomeScreen',

	requires: [
		'Ext.Button'
	],

	config: {
		hidden: false,
		hideAnimation: 'flip',
		id: 'WelcomeScreen',
		itemId: 'WelcomeScreen',
		items: [
			{
				xtype: 'component',
				hidden: false,
				html: '<center><img src ="resources/img/localbuzzicon.png"/><br><div style="text-align:center;"><h3 style="color:#00529D"><b>Welcome to <br><br>Local Buzz For Merchants</h3></div></center>',
				id: 'text1',
				left: '12%',
				style: 'word-wrap:break-word;font-family:Arial;font-size:6vw',
				top: '15%'
			},
			{
				xtype: 'button',
				handler: function(button, e) {
					Ext.Viewport.getActiveItem().destroy();
					var view = Ext.Viewport.add({xtype:'Login'});
					Ext.Viewport.setActiveItem(view);
				},
				height: '9vh',
				hidden: false,
				left: '20%',
				margin: '50 0 0 0',
				style: 'font-size:5vw;font-family:Arial',
				top: '35%',
				ui: 'action',
				width: '60%',
				text: 'Login'
			}
		],
		listeners: [
			{
				fn: 'onWelcomeScreenInitialize',
				event: 'initialize'
			}
		]
	},

	onWelcomeScreenInitialize: function(component, eOpts) {

		FacebookInAppBrowser.settings.appId = '900651756709444';
		FacebookInAppBrowser.settings.redirectUrl = 'http://www.appsonmobile.com';
		FacebookInAppBrowser.settings.permissions = 'email';
		        // Optional
		FacebookInAppBrowser.settings.timeoutDuration = 7500;
		FacebookInAppBrowser.getInfo(function(response) {

		if (response) {

			var view = Ext.Viewport.add({
		                        xtype: 'Login'
		                    });

		                Ext.Viewport.setActiveItem(view);
		            }
		});

	}

});