/*
 * File: app/view/contactinfo.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.contactinfo', {
	extend: 'Ext.form.Panel',
	alias: 'widget.contactinfo',

	requires: [
		'Contact.view.Picture',
		'Ext.Toolbar',
		'Ext.Button',
		'Ext.Spacer',
		'Ext.Img',
		'Ext.field.TextArea'
	],

	config: {
		border: 5,
		id: 'info',
		itemId: 'info',
		style: 'background;#fff',
		styleHtmlContent: true,
		modal: true,
		scrollable: false,
		layout: {
			type: 'vbox',
			align: 'stretchmax'
		},
		items: [
			{
				xtype: 'toolbar',
				cls: 'toolbarCls',
				docked: 'top',
				ui: 'plain',
				items: [
					{
						xtype: 'button',
						docked: 'right',
						hidden: false,
						itemId: 'editButton',
						padding: '5 0 0 0',
						style: 'color:#00529D',
						ui: 'plain',
						width: '20%',
						iconCls: 'compose'
					},
					{
						xtype: 'component',
						cls: 'contact-name',
						disabled: true,
						html: '<b>First Name</b>',
						id: 'nameTxt',
						itemId: 'nameTxt',
						padding: '15 5 5 15'
					},
					{
						xtype: 'spacer',
						height: 11,
						width: 18
					}
				]
			},
			{
				xtype: 'picture',
				flex: 1,
				docked: 'top',
				height: '30%',
				margin: '5 5 5 5'
			},
			{
				xtype: 'textfield',
				cls: [
					'icon-phone',
					'customfield1'
				],
				disabled: false,
				height: '',
				hidden: false,
				itemId: 'phoneNumber',
				margin: '',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				name: 'phoneNumber',
				readOnly: true
			},
			{
				xtype: 'textfield',
				cls: [
					'icon-email',
					'customfield1'
				],
				disabled: false,
				height: '',
				hidden: false,
				itemId: 'email',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				label: '',
				name: 'emailAddress',
				readOnly: true
			},
			{
				xtype: 'textfield',
				cls: [
					'icon-globe',
					'customfield1'
				],
				disabled: false,
				height: '',
				hidden: false,
				itemId: 'websiteDisplayName',
				padding: '10 10 10 10',
				style: 'font-size:2px !important',
				clearIcon: false,
				name: 'websiteDisplayName',
				readOnly: true
			},
			{
				xtype: 'textareafield',
				baseCls: '',
				cls: [
					'icon-location',
					'customfield1'
				],
				disabled: false,
				height: '12vh',
				hidden: false,
				html: '',
				itemId: 'address',
				maxHeight: '',
				minHeight: '',
				padding: '10 10 10 10',
				style: '\'font-size:3.5vw;font-family: arial\'',
				clearIcon: false,
				name: 'address',
				readOnly: true,
				maxRows: 2
			},
			{
				xtype: 'textfield',
				disabled: false,
				height: '',
				hidden: true,
				itemId: 'phoneNumber1',
				margin: '',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				name: 'city',
				readOnly: true
			},
			{
				xtype: 'textfield',
				disabled: false,
				height: '',
				hidden: true,
				itemId: 'phoneNumber2',
				margin: '',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				name: 'state',
				readOnly: true
			},
			{
				xtype: 'textfield',
				disabled: false,
				height: '',
				hidden: true,
				itemId: 'phoneNumber3',
				margin: '',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				name: 'zipcode',
				readOnly: true
			},
			{
				xtype: 'textfield',
				disabled: false,
				height: '',
				hidden: true,
				itemId: 'phoneNumber4',
				margin: '',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				name: 'pictureURL',
				readOnly: true
			},
			{
				xtype: 'textfield',
				disabled: false,
				height: '',
				hidden: true,
				itemId: 'phoneNumber5',
				margin: '',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				name: 'customerId',
				readOnly: true
			},
			{
				xtype: 'textfield',
				disabled: false,
				height: '',
				hidden: true,
				itemId: 'phoneNumber6',
				margin: '',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				name: 'category',
				readOnly: true
			},
			{
				xtype: 'textfield',
				disabled: false,
				height: '',
				hidden: true,
				itemId: 'phoneNumber7',
				margin: '',
				minWidth: '',
				padding: '10 10 10 10',
				clearIcon: false,
				name: 'businessName',
				readOnly: true
			}
		],
		listeners: [
			{
				fn: 'onInfoPainted',
				event: 'painted'
			}
		]
	},

	onInfoPainted: function(element, eOpts) {
		var storeUserDetails = Ext.getStore('UserDetails');
		storeUserDetails.load();
		var customerId;
		var businessName;
		var date = new Date();

		var today = Ext.Date.format(date, 'n/j/Y');

		storeUserDetails.each(function(record){
			//console.log('StoreUserDetails : ' +record.get('customerId'));
			customerId = record.get('customerId');
			businessName = record.get('businessName');

		});

		var record = Ext.getStore('MyJsonPStore').findRecord('customerId',customerId);

		this.setRecord(record);
	},

	setRecord: function(record) {

		this.callParent(arguments);




		if (record) {


			var name = record.get('businessName');



			var customerId = record.get('customerId');

			this.down('#nameTxt').setHtml(name);

		   //this.down('contactpic').setData(record.data);
















		}





	}

});