/*
 * File: app/view/DealPicture.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.DealPicture', {
	extend: 'Ext.Panel',
	alias: 'widget.dealPicture',

	requires: [
		'Ext.XTemplate',
		'Ext.Toolbar',
		'Ext.Button'
	],

	config: {
		fullscreen: true,
		height: '100%',
		itemId: 'dealPicture',
		left: 'dealPicture',
		style: 'overflow: hidden;background:#fff',
		styleHtmlContent: true,
		width: '100%',
		autoDestroy: false,
		scrollable: false,
		tpl: [
			'<img src="{dealPictureURL}" style="margin:5px 5px 5px 5px;height:100%;width:100%;border:1px groove #C0C0C0;"/>'
		],
		layout: {
			type: 'vbox',
			align: 'stretchmax'
		},
		items: [
			{
				xtype: 'toolbar',
				cls: 'toolbarCls',
				docked: 'top',
				ui: 'plain',
				width: '100%',
				scrollable: false,
				layout: {
					type: 'hbox',
					align: 'stretchmax'
				},
				items: [
					{
						xtype: 'button',
						cls: 'icon-back-button',
						itemId: 'dealBackBtn',
						style: 'font-size:8vw',
						ui: 'plain'
					},
					{
						xtype: 'button',
						cls: 'icon-share',
						docked: 'right',
						itemId: 'share',
						minHeight: '100%',
						style: 'border:none;font-size:7vw',
						ui: 'plain',
						iconAlign: 'center',
						text: ''
					}
				]
			}
		]
	}

});