/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Login', {
	extend: 'Ext.Container',

	config: {
		maxHeight: '',
		style: '',
		styleHtmlContent: true,
		layout: {
			type: 'card',
			animation: 'pop'
		},
		listeners: [
			{
				fn: 'onContainerPainted',
				event: 'painted'
			}
		]
	},

	onContainerPainted: function(element, eOpts) {




		// Settings.
		FacebookInAppBrowser.settings.appId = '900651756709444';
		FacebookInAppBrowser.settings.redirectUrl = 'http://appsonmobile.com';
		FacebookInAppBrowser.settings.permissions = 'email';

		// Optional
		FacebookInAppBrowser.settings.timeoutDuration = 7500;

		// Login(accessToken will be stored trough localStorage in 'accessToken');
		FacebookInAppBrowser.login({
			send: function() {
				console.log('login opened');
			},
			success: function(access_token) {
				console.log('done, access token: ' + access_token);

			},
			denied: function() {
				console.log('user denied');
			},
			timeout: function(){
				console.log('a timeout has occurred, probably a bad internet connection');
			},
			complete: function(access_token) {
				console.log('window closed');
				if(access_token) {
					console.log(access_token);
				} else {
					console.log('no access token');
				}
			},
			userInfo: function(userInfo) {
				if(userInfo) {
					var userInf = JSON.stringify(userInfo);
					console.log(userInf);

					var info = userInf.split("\",\"");

					var tmp = info[0].split("\":\"");
					var email = tmp[1];
					//console.log(email);
					tmp = info[1].split("\":\"");
					var loginName = tmp[1];

					tmp = info[2].split("\":\"");
					var gender = tmp[1];

					tmp = info[3].split("\":\"");
					var userId = tmp[1];

					var record = Ext.getStore('MyJsonPStore').findRecord('emailAddress','sterling@sterling.com',0,true,false,false);
					//console.log(store.getData());
					//store.loadRecord();
					//var view = Ext.create('Contact.view.Info');
					//view.setRecord(record.getRecord());
					//console.log(view.getData());
					//Ext.Viewport.setActiveItem(view);


					var storeUserDetails = Ext.getStore('UserDetails');
					storeUserDetails.removeAll();

					storeUserDetails.add({'customerId' : record.get('customerId'),
										  'email': email,
										  'businessName': record.get('businessName')});



					var view = Ext.Viewport.add({xtype:'panel'});
					//view.getComponent('home').setRecord(record);
					Ext.Viewport.getActiveItem().destroy();
					Ext.Viewport.setActiveItem(view);



				} else {
					console.log('no user info');
				}
			}
		});
	}

});