/*
 * File: app/view/panel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.panel', {
	extend: 'Ext.tab.Panel',
	alias: 'widget.panel',

	requires: [
		'Contact.view.contactinfo',
		'Contact.view.DealsPanel',
		'Ext.form.Panel',
		'Ext.tab.Bar',
		'Ext.tab.Panel'
	],

	config: {
		itemId: 'panel',
		items: [
			{
				xtype: 'container',
				title: 'Home',
				iconCls: 'icon-home',
				height: '',
				id: 'home',
				itemId: 'home',
				items: [
					{
						xtype: 'contactinfo',
						height: '100%'
					}
				]
			},
			{
				xtype: 'container',
				title: 'Manage Buzz',
				iconCls: 'icon-bubbles',
				items: [
					{
						xtype: 'DealsPanel',
						height: '100%'
					}
				]
			},
			{
				xtype: 'tabpanel',
				title: 'BuzzOMeter',
				iconCls: 'icon-buzzometer',
				id: 'buzzometer',
				itemId: 'buzzometer',
				styleHtmlContent: true,
				items: [
					{
						xtype: 'container',
						title: 'Buzz Popularity',
						height: '100%',
						html: '<div id="chart1"></div>',
						itemId: 'mypanel',
						styleHtmlContent: true,
						listeners: [
							{
								fn: function(element, eOpts) {
									var storeUserDetails = Ext.getStore('UserDetails');
									storeUserDetails.load();
									var customerId;
									var businessName;

									storeUserDetails.each(function(record){
										//console.log('StoreUserDetails : ' +record.get('customerId'));
										customerId = record.get('customerId');
										businessName = record.get('businessName');

									});




									// Set a callback to run when the Google Visualization API is loaded.
									google.charts.setOnLoadCallback(drawChart);
									function drawChart() {


										//Bar Chart
										var dataBarChart = new google.visualization.DataTable();
										var dealName=[];
										var numberOfClicks=[];
										dataBarChart.addColumn('string', 'dealName');

										dataBarChart.addColumn('number', 'numberOfClicks');

										$.getJSON('http://services.appsonmobile.com/analytics/v3/' + customerId,function(json){
											for(var i=0,j=i;i<json.totalResults;i++,j++){

												dealData = json.rows[i].toString();

												tmp = dealData.split(",");
												if(i===0){
													dealName[0] = tmp[0];
													numberOfClicks[0] = parseInt(tmp[2],10);
												}
												else {
													for(var m =i-1;m<i;m++) {
														if(tmp[0]===dealName[m]){
															numberOfClicks[m] = numberOfClicks[m] + parseInt(tmp[2],10);
															j--;
														}

														else {

															dealName[j] = tmp[0];
															numberOfClicks[j] = parseInt(tmp[2],10);
														}
													}

												}
											}


											for( j=0;j<numberOfClicks.length;j++){
												dataBarChart.addRow(
												[dealName[j],numberOfClicks[j]]

												);

											}



											// Set chart options
											var optionsBarChart = {
												vAxis: {
													title: 'Number of Views',
													titleTextStyle: {
														color: '#00529D',
														fontSize: 16
													},

													minValue: 0,
													gridlines: { count: -1}
												},
												hAxis: {
													title: 'Buzz Name',
													titleTextStyle: {
														color: '#00529D',
														fontSize: 16
													}
												},
												legend:'none',
												height:'400',
												orientation:'horizontal',

												bar: {
													groupWidth: 20
												}
											};
											// Instantiate and draw our chart, passing in some options.
											var chartBar = new google.visualization.BarChart(document.getElementById('chart1'));
											chartBar.draw(dataBarChart, optionsBarChart);



										});
									}

								},
								event: 'painted'
							}
						]
					},
					{
						xtype: 'container',
						title: 'User Location',
						height: '100%',
						html: '<div id="chart2"></div>',
						itemId: 'mypanel1',
						styleHtmlContent: true,
						listeners: [
							{
								fn: function(element, eOpts) {
									var storeUserDetails = Ext.getStore('UserDetails');
									storeUserDetails.load();
									var customerId;
									var businessName;

									storeUserDetails.each(function(record){
										//console.log('StoreUserDetails : ' +record.get('customerId'));
										customerId = record.get('customerId');
										businessName = record.get('businessName');

									});

									var dealName=[];



									// Set a callback to run when the Google Visualization API is loaded.
									google.charts.setOnLoadCallback(drawChart);
									function drawChart() {

										// Create the data table.
										var data = new google.visualization.DataTable();
										var zipcode=[];
										var numberOfHits=[];

										//data.addColumn('string', 'dealName');
										data.addColumn('string', 'zipcode');
										data.addColumn('number', 'NumberOfHits');


										$.getJSON('http://services.appsonmobile.com/analytics/v3/' + customerId,function(json){
											for(var i=0,j=i;i<json.totalResults;i++,j++){

												dealData = json.rows[i].toString();
												tmp = dealData.split(",");
												dealName[i] = tmp[0];
												if(zipcode[0]) {

													for(var k=0;k<j;k++)
													if(tmp[1]=== zipcode[k]) {

														numberOfHits[k]= numberOfHits[k] + parseInt(tmp[2],10);
														j--;
													}
													else {
														zipcode[j] = tmp[1];
														numberOfHits[j] = parseInt(tmp[2],10);
													}
												}
												else {
													zipcode[j] = tmp[1];
													numberOfHits[j] = parseInt(tmp[2],10);
												}








											}

											for(j=0;j< zipcode.length;j++) {
												data.addRow(
												[zipcode[j],parseInt(numberOfHits[j],10)]
												);
											}
											// Set chart options
											var options = {

												'pieHole':0.4,
												'pieSliceTextStyle': {
													color: 'black',


												},
												height:'500',
												width:'300',
												legend:'top'

											};
											// Instantiate and draw our chart, passing in some options.
											var chart = new google.visualization.PieChart(document.getElementById('chart2'));
											chart.draw(data, options);



										});




									}

								},
								event: 'painted'
							}
						]
					}
				],
				tabBar: {
					docked: 'top',
					styleHtmlContent: true
				}
			}
		],
		tabBar: {
			docked: 'bottom',
			padding: '35 40 0 40',
			style: 'color:#c0c0c0;background:#FFF;font-size:4vw',
			ui: 'plain',
			layout: {
				type: 'hbox',
				align: 'end',
				pack: 'justify'
			}
		}
	}

});