/*
 * File: app/view/Picture.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Picture', {
	extend: 'Ext.Img',
	alias: 'widget.picture',

	config: {
		html: '',
		id: 'picture',
		itemId: 'picture',
		padding: '5 5 5 5',
		listeners: [
			{
				fn: 'onImagePainted',
				event: 'painted'
			}
		]
	},

	onImagePainted: function(element, eOpts) {

		var storeUserDetails = Ext.getStore('UserDetails');
		storeUserDetails.load();
		var customerId;

		var store = Ext.getStore('MyJsonPStore');
		storeUserDetails.each(function(record){
			//console.log('StoreUserDetails : ' +record.get('customerId'));
			customerId = record.get('customerId');
			businessName = record.get('businessName');

		});

		store.sync();
		store.load();
		var record = Ext.getStore('MyJsonPStore').findRecord('customerId',customerId);

		this.setSrc(record.get('pictureURL'));
	}

});