/*
 * File: app/controller/Contacts.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.controller.Contacts', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.MessageBox'
    ],

    config: {
        stores: [
            'MyJsonPStore'
        ],

        refs: {
            contactinfo: {
                autoCreate: true,
                selector: 'contactinfo',
                xtype: 'contactinfo'
            },
            contactlist: {
                autoCreate: true,
                selector: 'contactlist',
                xtype: 'contactlist'
            }
        },

        control: {
            "dataview": {
                itemtap: 'onContactItemTap'
            },
            "button#infoBackBtn": {
                tap: 'onInfoBackBtnTapHome'
            },
            "favoriteview": {
                activate: 'onFavoriteViewActivate'
            },
            "list": {
                activate: 'onListActivate'
            },
            "contactpic": {
                change: 'onContactPickerChange'
            }
        }
    },

    onContactItemTap: function(dataview, index, target, record, e, eOpts) {
        var info = this.getContactinfo();
        info.setRecord(record);
        Ext.Viewport.setActiveItem(info);

    },

    onInfoBackBtnTapHome: function(button, e, eOpts) {
        Ext.Viewport.setActiveItem(0);

    },

    onFavoriteViewActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var ds = Ext.StoreManager.lookup('MyJsonPStore');
        ds.filter('isFavorite', true);
    },

    onListActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var ds = Ext.StoreManager.lookup('MyJsonPStore');
        ds.clearFilter();
    },

    onContactPickerChange: function(picker, value, eOpts) {
        var currentForm = Ext.Viewport.getActiveItem();
        var record = currentForm.getRecord();
        if (record) {
            record.set('picture', value);
            record.commit();
            currentForm.setRecord(record);
        }

    }

});