/*
 * File: app/view/BuzzOMeter.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.BuzzOMeter', {
	extend: 'Ext.Panel',
	alias: 'widget.buzzometer',

	config: {
		listeners: [
			{
				fn: 'onPanelActivate',
				event: 'activate'
			}
		]
	},

	onPanelActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
		var dealData;
		var dataTable=Ext.getStore('AnalyticsStore');
		var dealName;
		var zipcode;
		var numberOfHits;
		$.getJSON("http://services.appsonmobile.com/analytics/v3/04",function(json){
			for(var i = 0;i<json.totalResults;i++){

				dealData = (json.rows[i]).toString();
				var tmp = dealData.split(",");
				console.log(tmp.length);
				dealName = tmp[0];
				zipcode = tmp[1];
				numberOfHits = tmp[2];



				/*console.log(dealData);
				console.log(dealName);
				console.log(zipcode);
				console.log(numberOfHits);*/





			}
		});
	}

});