/*
 * File: app/view/Picture.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Picture', {
	extend: 'Ext.Container',
	alias: 'widget.contactpic',

	requires: [
		'Ext.XTemplate'
	],

	config: {
		overflow: 'hidden',
		id: 'contactpic',
		itemId: 'contactpic1',
		margin: '5 5 5 5',
		padding: '',
		style: 'overflow: hidden;border:1px groove #000;background:none',
		ui: '',
		scrollable: false,
		tpl: [
			'',
			'	<img src="{pictureURL}" style="width:100%;height:30%"/>',
			'	'
		],
		layout: {
			type: 'vbox',
			align: 'stretchmax'
		}
	}

});