/*
 * File: app/view/UploadDealForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.UploadDealForm', {
	extend: 'Ext.form.Panel',
	alias: 'widget.UploadDealForm',

	requires: [
		'Ext.field.DatePicker',
		'Ext.picker.Date',
		'Ext.Button',
		'Ext.field.File',
		'Ext.Spacer'
	],

	config: {
		cls: 'customfield',
		height: '100%',
		minHeight: '',
		style: 'background:white',
		enctype: 'multipart/form-data',
		url: 'http://services.appsonmobile.com/uploadS3',
		items: [
			{
				xtype: 'textfield',
				cls: 'customfield',
				margin: '5 5 5 5 ',
				padding: '',
				style: 'border:1px solid #C0C0C0!important',
				styleHtmlContent: true,
				width: '',
				clearIcon: false,
				label: 'Name',
				labelWidth: '35%',
				name: 'DealName'
			},
			{
				xtype: 'selectfield',
				cls: 'customfield',
				itemId: 'dealStatus',
				margin: '5 5 5 5 ',
				maxHeight: '',
				style: '',
				styleHtmlContent: true,
				label: 'Status',
				labelWidth: '35%',
				labelWrap: true,
				name: 'DealStatus',
				value: 'Active',
				placeHolder: 'Active',
				autoSelect: false,
				options: [
					{
						text: 'Active',
						value: 'Active'
					},
					{
						text: 'Expired',
						value: 'Expired'
					}
				]
			},
			{
				xtype: 'datepickerfield',
				cls: [
					'customfield',
					'x-field-select'
				],
				id: 'DealStartDate',
				itemId: 'DealStartDate',
				margin: '5 5 5 5 ',
				styleHtmlContent: true,
				width: '97%',
				label: 'Start Date',
				labelWidth: '35%',
				labelWrap: true,
				name: 'DealStartDate',
				value: {
					day: new Date().getDate(),
					month: (new Date().getMonth()+1),
					year: new Date().getFullYear()
				},
				placeHolder: 'mm/dd/yyyy',
				autoSelect: false,
				usePicker: true,
				dateFormat: 'm/d/Y',
				picker: {
					itemId: 'mydatepicker3',
					styleHtmlContent: true,
					stretchX: false,
					yearFrom: 2016
				}
			},
			{
				xtype: 'datepickerfield',
				cls: [
					'customfield',
					'x-field-select'
				],
				itemId: 'DealEndDate',
				margin: '5 5 5 5 ',
				styleHtmlContent: true,
				width: '97%',
				label: 'End Date',
				labelWidth: '35%',
				name: 'DealEndDate',
				value: {
					day: new Date().getDate(),
					month: (new Date().getMonth()+1),
					year: new Date().getFullYear()
				},
				placeHolder: 'mm/dd/yyyy',
				usePicker: true,
				picker: {
					styleHtmlContent: true,
					yearFrom: 2016
				}
			},
			{
				xtype: 'filefield',
				cls: 'customfield',
				id: 'myfilefield',
				itemId: 'myfilefield',
				margin: '5 5 5 5 ',
				style: 'color:white',
				styleHtmlContent: true,
				clearIcon: false,
				label: 'Image',
				labelWidth: '35%',
				labelWrap: true,
				name: 'fileUpload',
				capture: 'camera'
			},
			{
				xtype: 'spacer',
				maxHeight: ''
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'customerId'
			},
			{
				xtype: 'textfield',
				hidden: true,
				name: 'businessName'
			},
			{
				xtype: 'container',
				height: 140,
				margin: '10 10 10 10 10',
				layout: 'fit',
				scrollable: false,
				items: [
					{
						xtype: 'spacer',
						maxWidth: '',
						minWidth: ''
					},
					{
						xtype: 'button',
						handler: function(button, e) {
							Ext.Viewport.getActiveItem().destroy();

						},
						height: '20%',
						style: 'font-size:5vw!important',
						styleHtmlContent: true,
						ui: 'decline',
						width: '40%',
						text: 'Cancel'
					},
					{
						xtype: 'button',
						handler: function(button, e) {


							var uForm = this.up('UploadDealForm') ;


							var file = uForm.getAt(4).getValue();

							//var dealStartDate = uForm.getAt(2).getValue().toDateString();
							//var dealEndDate = uForm.getAt(3).getValue();



							Ext.Date.format(uForm.getAt(2).getValue(),'n/j/Y');
							Ext.Date.format(uForm.getAt(3).getValue(),'n/j/Y');
							/*var startDate = uForm.getAt(2).getValue();

							var date = (startDate.getMonth()+1)+"/"+ startDate.getDate() + "/" + startDate.getFullYear();
							console.log(date);

							uForm.getAt(2).setValue(date);


							var startDate = uForm.getAt(3).getValue();

							var date = (startDate.getMonth()+1)+"/"+ startDate.getDate() + "/" + startDate.getFullYear();
							console.log(date);


							uForm.getAt(3).setValue(date);


							console.log(date);*/

							/*var startDate = dealStartDate.getDate();
							var startMonth = dealStartDate.getMonth()+1;
							var startYear = dealStartDate.getFullYear();

							var dealStart = startDate + "/" + startMonth + "/" + startYear ;

							console.log(dealStart);

							uForm.getAt(2).setValue(dealStart);

							var endDate = dealEndDate.getDate();
							var endMonth = dealEndDate.getMonth()+1;
							var endYear = dealEndDate.getFullYear();

							var dealEnd = endDate + "/" + endMonth + "/" + endYear ;

							uForm.getAt(3).setValue(dealEnd);
							console.log(dealEnd);*/





							if(file){



								uForm.submit({

									url :  'http://services.appsonmobile.com/uploadS3',
									xhr2:true,
									waitMsg : 'Please Wait...',
									timeout : 5000,


									scope: this,
									success: function(form,action) {
										Ext.getStore('MyDealsStore').load();

										Ext.Msg.alert('Success',action.msg);


										//console.log("Action Msg is : " +action.success);
										//Ext.Viewport.setActiveItem({xtype:'DealsPanel'});
										uForm.destroy();


									},

									failure: function(form,action) {
										Ext.getStore('MyDealsStore').load();
										Ext.Msg.alert('Failure',action.msg);


										console.log("Action Msg is : " + action.msg);
										//Ext.Viewport.setActiveItem({xtype:'DealsPanel'});
										uForm.destroy();


									}



								});
							}
							else {
								Ext.Msg.alert('Failure','No Image to Upload');
								uForm.destroy();


							}


















						},
						docked: 'right',
						height: '20%',
						itemId: 'submit',
						style: 'font:size:4vw',
						styleHtmlContent: true,
						ui: 'confirm',
						width: '30%',
						text: 'Submit'
					}
				]
			}
		]
	}

});