/*
 * File: app/controller/Contacts.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.controller.Contacts', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.MessageBox'
    ],

    config: {
        stores: [
            'MyJsonPStore',
            'MyDealsStore'
        ],

        refs: {
            contactinfo: {
                autoCreate: true,
                selector: 'contactinfo',
                xtype: 'contactinfo'
            },
            contactlist: {
                autoCreate: true,
                selector: 'contactlist',
                xtype: 'contactlist'
            },
            dealsinfo: {
                autoCreate: true,
                selector: 'dealsinfo',
                xtype: 'listofdeals'
            },
            dealpicture: {
                autoCreate: true,
                selector: 'dealpicture',
                xtype: 'dealpicture'
            },
            phoneNumber: 'textfield#phoneNumber',
            address: 'textfield#address'
        },

        control: {
            "dataview": {
                itemtap: 'onContactItemTap'
            },
            "button#infoBackBtn": {
                tap: 'onInfoBackBtnTapHome'
            },
            "favoriteview": {
                activate: 'onFavoriteViewActivate'
            },
            "contactpic": {
                change: 'onContactPickerChange'
            },
            "list": {
                activate: 'onListActivate'
            },
            "listofdeals": {
                itemtap: 'onListOfDealsItemTap'
            },
            "button#dealBackBtn": {
                tap: 'onDealBackBtnTap'
            },
            "textfield#phoneNumber": {
                focus: 'onPhoneNumberFocus'
            },
            "textfield#address": {
                focus: 'onAddressFocus'
            }
        }
    },

    onContactItemTap: function(dataview, index, target, record, e, eOpts) {
        var info = this.getContactinfo();
        info.setRecord(record);
        Ext.Viewport.setActiveItem(info);

    },

    onInfoBackBtnTapHome: function(button, e, eOpts) {
        var ds = Ext.StoreManager.lookup('MyJsonPStore');
        ds.clearFilter() ;
        Ext.Viewport.setActiveItem(0);

    },

    onFavoriteViewActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var ds = Ext.StoreManager.lookup('MyJsonPStore');
        ds.filter('isFavorite', true);
    },

    onContactPickerChange: function(picker, value, eOpts) {
        var currentForm = Ext.Viewport.getActiveItem();
        var record = currentForm.getRecord();
        if (record) {
            record.set('picture', value);
            record.commit();
            currentForm.setRecord(record);
        }

    },

    onListActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var ds = Ext.StoreManager.lookup('MyJsonPStore');
        ds.clearFilter();
    },

    onListOfDealsItemTap: function(dataview, index, target, record, e, eOpts) {
        var pic = this.getDealpicture();
        /*console.log("Data View is: ") ;
        console.log(dataview) ;
        console.log("Index is: " + index) ;
        console.log("Target is: ") ;
        console.log(target) ;
        console.log("Event is: ") ;
        console.log(e) ;
        console.log("Event Options is: ") ;
        console.log(eOpts) ;*/
        pic.setRecord(record);
        Ext.Viewport.setActiveItem(pic);




    },

    onDealBackBtnTap: function(button, e, eOpts) {
        var ds = Ext.StoreManager.lookup('MyJsonPStore');
        ds.clearFilter() ;
        var dealRecord = this.getContactinfo().getRecord() ;
        //console.log("Deal Record is:") ;
        //console.log(dealRecord) ;
        var customerId = dealRecord.get('customerId');
        //console.log("Customer Id is " + customerId) ;
        ds.filter('customerId', customerId);

        var customerData = ds.getData().getAt(0) ;
        //console.log("Customer Data is:") ;
        //console.log(customerData) ;

        var info = this.getContactinfo();
        info.setRecord(customerData);
        Ext.Viewport.setActiveItem(info);
        //Ext.Viewport.setActiveItem('contactinfo') ;





    },

    onPhoneNumberFocus: function(textfield, e, eOpts) {
        console.log(e);
        numberToDial = textfield.getValue();
        textfield.blur();
        e.destroy();
        e.stopEvent();
        window.location = 'tel:'+ numberToDial ;
    },

    onAddressFocus: function(textfield, e, eOpts) {
        console.log(textfield.getValue());
        var queryString = encodeURIComponent(textfield.getValue());
        var url = 'geo:0,0?q='  + queryString;
        textfield.blur();
        e.stopEvent();
        e.destroy();
        Ext.device.Device.openURL(url);
    }

});