/*
 * File: app/store/MyDealsStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.store.MyDealsStore', {
	extend: 'Ext.data.Store',

	requires: [
		'Contact.model.Deal',
		'Ext.data.proxy.JsonP',
		'Ext.data.reader.Json',
		'Ext.data.writer.Json'
	],

	config: {
		autoLoad: true,
		model: 'Contact.model.Deal',
		storeId: 'MyDealsStore',
		proxy: {
			type: 'jsonp',
			url: 'http://services.appsonmobile.com/deals',
			reader: {
				type: 'json'
			},
			writer: {
				type: 'json',
				encode: true
			}
		},
		listeners: [
			{
				fn: 'onJsonstoreAddrecords',
				event: 'addrecords'
			},
			{
				fn: 'onJsonstoreRemoverecords',
				event: 'removerecords'
			}
		]
	},

	onJsonstoreAddrecords: function(store, records, eOpts) {
		store.load();
	},

	onJsonstoreRemoverecords: function(store, records, indices, eOpts) {
		store.load();
	}

});